/**
 * Generates public/sitemap.xml from the single route list in src/lib/paths.ts.
 *
 * Written as a script rather than a hand-maintained XML file so the sitemap can
 * never drift out of sync with the routes — a stale sitemap advertising a dead
 * URL is worse than no sitemap at all.
 *
 * Run: node scripts/generate-sitemap.mjs
 */

import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

// Read the constants straight out of the TS source so there is exactly one
// place that defines the origin and the route list.
const src = readFileSync(resolve(root, "src/lib/paths.ts"), "utf8");

const siteUrl = /export const SITE_URL = "([^"]+)"/.exec(src)?.[1];
if (!siteUrl) throw new Error("Could not read SITE_URL from src/lib/paths.ts");

const cnPrefix = /export const CN_PREFIX = "([^"]+)"/.exec(src)?.[1];
if (!cnPrefix) throw new Error("Could not read CN_PREFIX from src/lib/paths.ts");

const routesBlock = /export const ROUTES = \[([\s\S]*?)\] as const;/.exec(src)?.[1];
if (!routesBlock) throw new Error("Could not read ROUTES from src/lib/paths.ts");
const routes = [...routesBlock.matchAll(/"([^"]+)"/g)].map((m) => m[1]);

// ROUTES spreads EXHIBITION_ROUTES rather than listing those paths inline, so
// scanning for quoted strings alone silently misses them. It did exactly that
// once, and the three exhibition pages were left out of the sitemap.
if (routesBlock.includes("...EXHIBITION_ROUTES")) {
  const block = /export const EXHIBITION_ROUTES = \[([\s\S]*?)\] as const;/.exec(src)?.[1];
  if (!block) throw new Error("ROUTES spreads EXHIBITION_ROUTES but that list was not found");
  routes.push(...[...block.matchAll(/"([^"]+)"/g)].map((m) => m[1]));
}

// Any spread we have not taught this script about would be a silent omission,
// which is worse than a failed build.
const unknownSpread = /\.\.\.(?!EXHIBITION_ROUTES)([A-Z_]+)/.exec(routesBlock);
if (unknownSpread) {
  throw new Error(
    `ROUTES spreads ${unknownSpread[1]}, which this generator does not expand. ` +
      "Add it above, or those routes will be missing from the sitemap.",
  );
}

/** Mirrors localizedPath() in src/lib/paths.ts. */
const localized = (path, lang) => {
  if (lang === "en") return path;
  return path === "/" ? cnPrefix : cnPrefix + path;
};

/** Mirrors absoluteUrl() in src/lib/paths.ts. */
const url = (path, lang = "en") => {
  const p = localized(path, lang);
  return `${siteUrl}${p === "/" ? "/" : p}`;
};

// Home is the entry point; the service and network pages rank just below it.
// The legal pages are deliberately low — they must be crawlable and linked, but
// they should never outrank a service page for a brand query.
const LOW = ["/privacy", "/terms"];
const priority = (path) =>
  path === "/"
    ? "1.0"
    : LOW.includes(path)
      ? "0.3"
      : path === "/contact"
        ? "0.6"
        : path === "/faqs"
          ? "0.7"
          : "0.8";
const changefreq = (path) => (path === "/" ? "weekly" : LOW.includes(path) ? "yearly" : "monthly");

const lastmod = new Date().toISOString().slice(0, 10);

const entries = routes
  .flatMap((path) =>
    ["en", "cn"].map(
      (lang) => `  <url>
    <loc>${url(path, lang)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq(path)}</changefreq>
    <priority>${priority(path)}</priority>
    <xhtml:link rel="alternate" hreflang="en" href="${url(path, "en")}" />
    <xhtml:link rel="alternate" hreflang="zh-Hans" href="${url(path, "cn")}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${url(path, "en")}" />
  </url>`,
    ),
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml"
>
${entries}
</urlset>
`;

writeFileSync(resolve(root, "public/sitemap.xml"), xml, "utf8");
console.log(`sitemap.xml written — ${routes.length} routes × 2 languages = ${routes.length * 2} URLs`);
